service: congressional-trades

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10

package:
  exclude:
    - node_modules/**

functions:
  run-rebalance:
    handler: src/lambda_function.lambda_handler

plugins:
  - serverless-python-requirements
 
custom:
  pythonRequirements:
    dockerizePip: non-linux
