service: congressional-trades

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10

package:
  exclude:
    - node_modules/**

functions:
  run-rebalance:
    handler: main.rebalance
    timeout: 60
    environment:
      ALPACA_API_KEY: ${env:ALPACA_API_KEY}
      ALPACA_API_SECRET: ${env:ALPACA_API_SECRET}
    events:
      - eventBridge:
          name: run-every-monday
          schedule: cron(0 13 ? * MON *)

plugins:
  - serverless-python-requirements
 
custom:
  pythonRequirements:
    dockerizePip: non-linux
